add evaluation code
deepvk/didi pull request #2
Opened 2022-11-15 09:02 UTC by pkseniya

2022-11-16 10:50 UTC, shmpanski commented on scripts/evaluate_model.py
> +from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
Для чистоты кода хорошо использовать `isort` или похожие утилиты из `pycharm` / `vscode`
В `pycharm` есть [целый раздел](https://www.jetbrains.com/help/pycharm/creating-and-optimizing-imports.html#optimize-imports) про оптимизацию импортов

2022-11-16 10:52 UTC, shmpanski commented on scripts/evaluate_model.py
> +        np.random.seed(42)
Есть ли необходимость хардкодить здесь `seed`?
Возможно, стоит вынести его в аргументы или отдельную функцию "`seed_all`"

2022-11-16 11:03 UTC, shmpanski commented on scripts/evaluate_model.py
> +            f1s.append(bleu_score([generated], [candidate], max_n=1, weights=[1]))
Переменная где-то определена?

2022-11-16 11:03 UTC, shmpanski commented on scripts/evaluate_model.py
> +            ).to(device)
Если предполагается использовать tokenizers только из huggingface, то имеет смысл занести токенизацию в `__getitem__` или сделать кастомную `collate_fn`

2022-11-16 12:15 UTC, SpirinEgor requested changes

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +    args = parser.parse_args()
Let's change structure a little bit, so `main` method would be more reusable, e.g. import from another script or notebook.

I prefer to make
- `def configure_arg_parser() -> ArgumentParser` -- function to create argument parser w/ all arguments and their description
- `def main(...)` -- main method accept all necessary args, i.e. model name and batch size
After make entrypoint would be like that:
```python
if __name__ == "__main__":
    _args = configure_arg_parser().parse_args()
    main(**vars(_args))  # or main(_args.model, _args.batch_size) if there is no many arguments
```

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +    parser.add_argument("-b", "--batch_size", type=int, default=64)
Don't forget to add help, this will help you to write less documentation

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +    tokenizer = AutoTokenizer.from_pretrained(args.model, truncation_side="left", padding_side="left")
Truncation and padding sides are model specific, why are you hard-coded this values?

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +        for batch in (pbar := tqdm(dataloader)):
I think this line is not pythonic. They add this functionality in 3.10, but I it reduce simplicity of code 😅
I suggest to define progress bar in separate expression.

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +            pbar.set_description("Calculating metrics")
You can set description in progress bar initialisation.

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +                max_length=128,
This should be either argument to pass or extracted from the model. Something like minimum between model maximum len and what use pass.

Or if you don't want to pass len with arguments, you can define global constant, so we can easily change it in future.

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +            reply_ids = model.generate(**inputs, max_length=64)
Generate has a lot of arguments to tune, for now you are using greedy decoding. But there is an option to use beam search or different sampling strategies. Let's define a global dict with parameters for this function. Most important: `max_length`, `do_sample`, `num_beams`, `top_k`, `top_p`, `repetition_penalty`

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +            pbar.set_description("Creating dataset")
Same comments about progress bar

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +        np.random.seed(42)
Let's make seed global constant at top of the script.
```python
SEED = 42
```

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +
Have some questions here:
- Negative candidates never will be from the same dialog. Is it okay?
- Negative candidates always bot messages. Is it also okay?

I also suggest you to simplify this logic: let's create an array with all possible negative candidates and the just sample from it.

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +                        dialog_ids = np.random.choice(ids, size=19, replace=False)
This `19` should dataset parameter, don't hard-code values

2022-11-16 12:15 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +        for i, dialog in (pbar := tqdm(enumerate(dataset["train"]))):
This cycle is too complex, let's split it into a few functions. For example, extracting samples from one dialog may be moved into a separate function.

2022-11-29 12:53 UTC, SpirinEgor requested changes

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +def configure_arg_parser():
Move this function to `scripts/evaluate_model.py`
1. You will never reuse it, this argument parser is specific only for one script
2. This function also describes evaluating parameters, so it is better to keep it in the main script. This way anyone can quickly check what and why they should specify.

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +class ConvAI2Dataset(Dataset):
This class you will use during model training. It is the main class for your data. So this should be in your sources. For example, in `src/data/dataset.py`

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +    """ConvAI2 Dataset"""
This docstring is kind of useless. Either add a dataset description or remove it.

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +            path (str): File path to ConvAI2 dataset
If you know that `path` has a `str` type then it is better to specify it in a pythonic way:
```python
def __init__(self, path: str):
```

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +            path (str): File path to ConvAI2 dataset
All in all, it is better to write type hints whenever it is possible

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +        persona = "your persona"
Let's move to class constant, `_PERSONA_PREFIX`

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +                if line[2 : 2 + len(persona)] == persona:
`if line[2:].startswith(self._PERSONA_PREFIX)`

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +        self.dataset = dataset
It's always good to log all information. So you are always aware of what happens in your code.
I suggest using [loguru](https://github.com/Delgan/loguru).

For example, in the dataset you can log some statistics at the end:
```python
from loguru import logger

...

logger.info(f"Init dataset w/ {len(dataset["context"]} dialog, # utterance {} ...")
```

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +def calculate_hits_ppl(model, tokenizer, dataset, max_len, device):
These functions also may be useful in model training, so let's move them into main sources. For example, `src/metrics.py`

2022-11-29 12:53 UTC, SpirinEgor commented on scripts/evaluation_utils.py
> +    loss_fn = nn.CrossEntropyLoss(reduction="none")
I think that there is no need for separate class, you can use [`torch.nn.functional.cross_entropy`](https://pytorch.org/docs/stable/generated/torch.nn.functional.cross_entropy.html#torch.nn.functional.cross_entropy)

2022-12-06 15:24 UTC, SpirinEgor commented on scripts/evaluate_model.py
> +    parser.add_argument("-m", "--diffusion", help="Seq2seq diffusion name from huggingface")
Diffusion name?

2022-12-06 15:24 UTC, SpirinEgor commented on src/metrics.py
> +    with torch.no_grad():
Just add decorator `@torch.no_grad()` to this function.

2022-12-06 15:24 UTC, SpirinEgor commented on src/metrics.py
> +    with torch.no_grad():
And you can use a decorator here too. This will avoid unnecessary nesting.

2022-12-12 11:46 UTC, SpirinEgor reviewed
🔥

2022-12-12 11:46 UTC, SpirinEgor commented on src/metrics.py
> +    ppl = torch.concat(ppls).float().median().item()
Why median for the perplexity?

2022-12-29 16:19 UTC, merged